
from solarsan import logging, signals
logger = logging.getLogger(__name__)


"""
SCST Log Policy
"""

'''
stop:
    [268487.520874] [1126]: scst: scst_acg_del_lun:3579:Removed LUN 1 from group iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019
    [268487.610378] [1126]: dev_vdisk: vdisk_detach:908:Detached virtual device r0 ("/dev/drbd/by-res/r0")
    [268487.610405] [1126]: scst: scst_unregister_virtual_device:1341:Detached from virtual device r0 (id 1)
    [268487.686205] [1126]: scst: scst_acg_del_lun:3579:Removed LUN 2 from group iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019
    [268487.762424] [1126]: dev_vdisk: vdisk_detach:908:Detached virtual device r1 ("/dev/drbd/by-res/r1")
    [268487.762501] [1126]: scst: scst_unregister_virtual_device:1341:Detached from virtual device r1 (id 2)
    [268487.850444] [2540]: target_destroy:227:Destroying target tid 1
[272559.741414] [2540]: scst: scst_unregister_target:687:Target iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019 for template iscsi unregistered successfully

start:
    [268491.920369] [2540]: iscsi_target_create:65:Creating target tid 2, name iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019
    [268491.920421] [2540]: scst: scst_register_target:572:Target iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019 for template iscsi registered successfully
    [268491.988798] [1126]: dev_vdisk: vdisk_report_registering:4273:Registering virtual vdisk_blockio device r0 (BLOCKIO, ROTATIONAL)
    [268491.993784] [1126]: dev_vdisk: vdisk_attach:872:Attached SCSI target virtual disk r0 (file="/dev/drbd/by-res/r0", fs=1023MB, bs=512, nblocks=2097016, cyln=1023)
    [268491.993814] [1126]: scst: scst_register_virtual_device:1264:Attached to virtual device r0 (id 3)
    [268492.070405] [1126]: scst: scst_acg_add_lun:3527:Added device r0 to group iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019 (LUN 1, rd_only 0)
    [268492.158451] [1126]: dev_vdisk: vdisk_report_registering:4273:Registering virtual vdisk_blockio device r1 (BLOCKIO, ROTATIONAL)
    [268492.158621] [1126]: dev_vdisk: vdisk_attach:872:Attached SCSI target virtual disk r1 (file="/dev/drbd/by-res/r1", fs=1023MB, bs=512, nblocks=2097016, cyln=1023)
    [268492.158649] [1126]: scst: scst_register_virtual_device:1264:Attached to virtual device r1 (id 4)
    [268492.223388] [1126]: scst: scst_acg_add_lun:3527:Added device r1 to group iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019 (LUN 2, rd_only 0)
    [268492.307738] [1126]: scst: scst_process_tgt_enable_store:2018:Using autogenerated rel ID 2 for target iqn.2012-01.net.locsol.solarsan.san0.x8664:sn.1e9962ceb019

browse portal:
    Apr 16 19:53:33 san0 iscsi-scstd: [info] Connect from 10.90.90.1:46602 to 10.90.90.50:3260

'''


@signals.check_log_entry.connect
def test_scst_log_policy(self, log):
    if not 'scst' in log.message:
        return
    logger.debug('SCST Log: %s', log.message)


'''
drbd boot:
[    4.589092] drbd: initialized. Version: 8.4.2 (api:1/proto:86-101)
[    4.589095] drbd: srcversion: D4E87CE96AA95060B684559
[    4.589097] drbd: registered as block device major 147
[    4.877892] d-con r0: Starting worker thread (from drbdsetup [2180])
[    4.878052] block drbd0: disk( Diskless -> Attaching )
[    4.880691] d-con r0: Method to ensure write ordering: flush
[    4.880694] block drbd0: max BIO size = 1048576
[    4.880698] block drbd0: drbd_bm_resize called with capacity == 2097016
[    4.880704] block drbd0: resync bitmap: bits=262127 words=4096 pages=8
[    4.880705] block drbd0: size = 1024 MB (1048508 KB)
[    4.881780] block drbd0: bitmap READ of 8 pages took 0 jiffies
[    4.881787] block drbd0: recounting of set bits took additional 0 jiffies
[    4.881789] block drbd0: 0 KB (0 bits) marked out-of-sync by on disk bit-map.
[    4.881793] block drbd0: disk( Attaching -> UpToDate )
[    4.881796] block drbd0: attached to UUIDs 172C2C3F8160352B:AF839B8A956D9B4C:60ECBCAEA44A4197:60EBBCAEA44A4197
[    4.994877] d-con r1: Starting worker thread (from drbdsetup [2203])
[    4.995071] block drbd1: disk( Diskless -> Attaching )
[    4.995840] d-con r1: Method to ensure write ordering: flush
[    4.995855] block drbd1: max BIO size = 1048576
[    4.995869] block drbd1: drbd_bm_resize called with capacity == 2097016
[    4.995878] block drbd1: resync bitmap: bits=262127 words=4096 pages=8
[    4.995881] block drbd1: size = 1024 MB (1048508 KB)
[    4.996305] block drbd1: bitmap READ of 8 pages took 1 jiffies
[    4.996310] block drbd1: recounting of set bits took additional 0 jiffies
[    4.996312] block drbd1: 0 KB (0 bits) marked out-of-sync by on disk bit-map.
[    4.996315] block drbd1: disk( Attaching -> UpToDate )
[    4.996317] block drbd1: attached to UUIDs 2833AF97F50B0039:4292977A9D364DD8:39D94770D443B979:39D84770D443B979
[    5.006888] d-con r0: conn( StandAlone -> Unconnected )
[    5.007054] d-con r0: Starting receiver thread (from drbd_w_r0 [2182])
[    5.009368] d-con r1: conn( StandAlone -> Unconnected )
[    5.009399] d-con r0: receiver (re)started
[    5.009410] d-con r0: conn( Unconnected -> WFConnection )
[    5.009551] d-con r1: Starting receiver thread (from drbd_w_r1 [2205])
[    5.009634] d-con r1: receiver (re)started
[    5.009645] d-con r1: conn( Unconnected -> WFConnection )
[   41.026661] block drbd1: role( Secondary -> Primary )
[   41.085881] block drbd0: role( Secondary -> Primary )

'''

"""
Target Log Policy
"""


class TargetLogPolicy(object):
    def __init__(self):
        pass

    def __call__(self, lw, log):
        pass


#target_log_policy = TargetLogPolicy()
#signals.check_log_entry.connect(target_log_policy)
